# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: https://inkeys.tech
title: inkeys
email: "n/o"
description: "A project dedicated to making keyboards more inclusive and accessible"

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: discord
    icon: discord
    url: https://discord.gg/fGUjnUuAVQ
  - title: knowledge base
    icon: book
    url: https://inkeys.wiki
  - title: transparency report
    icon: th-list
    url: https://inkeys.wiki/transparency
  - title: github
    icon: github
    url: https://github.com/inkeystech